org: marutyan21
app: rds
service: rds
frameworkVersion: '3'

custom:
  webpack:
    includeModules: false

package:
  individually: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: "*"

  environment:
    youtubeName: 'youtube-table-${sls:stage}'
    myTableName: my_table
    DB_NAME: rds
    USERNAME: postgres
    PASSWORD: root1234
    HOST:
      Fn::GetAtt: [ pgDB, Endpoint.Address ]
    PORT:
      Fn::GetAtt: [ pgDB, Endpoint.Port ]

functions:
  mostPopular:
    handler: handler.hello
    events:
      - http:
          path: you
          method: get
          cors: true

resources:
  Resources:
    pgSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Acess to Postgre
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '5432'
            ToPort: '5432'
            CidrIp: 0.0.0.0/0

    pgDB:
        Type: "AWS::RDS::DBInstance"
        Properties:
          DBName: rds
          AllocatedStorage: 5
          DBInstanceClass: "db.m6g.4xlarge"
          Engine: "postgres"
          MasterUsername: postgres
          MasterUserPassword: root1234
          VPCSecurityGroups:
            - Fn::GetAtt:
                - pgSecurityGroup
                - GroupId
        DeletionPolicy: "Snapshot"






